[package]
name = "zenoh-consensus"
version = "0.1.0"
authors = ["Hsiang-Jui Lin <jerry73204@gmail.com>", "Yi-Hung Kuo <50904241+eurc17@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh = "0.5.0-beta.8"
async-std = "1.9.0"
futures = "0.3.15"
uhlc = "0.3.0"
tokio = { version = "1.6.1", features = ["sync"] }
anyhow = "1.0.40"
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
derivative = "2.2.0"
dashmap = "4.0.2"
log = "0.4.14"
owning_ref = "0.4.1"

[patch.crates-io]
# zenoh = { git = "https://github.com/NEWSLabNTU/zenoh.git", branch = "newslab-patches" }
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", rev = "471f485acf883f27da06318b57b65291050aecfa" }
